<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name=base_radius value="0.0475"/>
    <xacro:property name=base_length value="0.045"/>
    <xacro:property name=base_mass value="0.5"/>

    <xacro:property name=rot_base_radius value="0.0475"/>
    <xacro:property name=rot_base_length value="0.01"/>
    <xacro:property name=rot_base_mass value="0.2"/>

    <xacro:property name=arm1_motor_x value="0.064"/>
    <xacro:property name=arm1_motor_y value="0.04"/>
    <xacro:property name=arm1_motor_z value="0.03"/>
    <xacro:property name=arm1_motor_mass value="0.5"/>

    <xacro:property name=arm1_bracket_origin value="-0.068 0.0125 0.0745"/>
    <xacro:property name=arm1_bracket_x value="0.068"/>
    <xacro:property name=arm1_bracket_y value="0.0125"/>
    <xacro:property name=arm1_bracket_z value="0.0745"/>
    <xacro:property name=arm1_bracket_mass value="0.15"/>

    <xacro:property name=arm1_joint_origin value="${arm1_bracket_x/2} -0.0075 0.022"/>

    <xacro:property name=arm2_bracket_origin value="-0.0265 -0.0125 0"/>
    <xacro:property name=arm1_bracket_x value="0.053"/>
    <xacro:property name=arm1_bracket_y value="0.025"/>
    <xacro:property name=arm1_bracket_z value="0.057"/>
    <xacro:property name=arm1_bracket_mass value="0.12"/>

    <xacro:property name=arm2_motor_x value="0.049"/>
    <xacro:property name=arm2_motor_y value="0.025"/>
    <xacro:property name=arm2_motor_z value="0.04"/>
    <xacro:property name=arm2_motor_mass value="0.5"/>

    <xacro:property name=arm2_joint_origin value="0.026 0 0.044"/>

    <xacro:property name=arm2_stem_radius value="0.006"/>
    <xacro:property name=arm2_stem_length value="0.07"/>
    <xacro:property name=arm2_stem_mass value="0.2"/>

    

 <!-- ___________________________________ colors ________________________________ -->

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

</robot>