controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_vel_cont:
      type: joint_trajectory_controller/JointGroupVelocityController

joint_vel_cont:
  ros__parameters:
    joints:
      - rot_base_joint
      - arm1_joint
      - arm2_joint
      - arm3_joint
      - left_claw_joint
      - right_claw_joint
    state_publish_rate: 50
    command_interfaces:
      - velocity
    allow_partial_joints_goal: true
