controller_manager:
  ros__parameters:
    update_rate: 100

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

trajectory_controller:
  ros__parameters:
    joints:
      - rot_base_joint
      - arm1_joint
      - arm2_joint
      - arm3_joint
      - left_claw_joint

    command_interfaces:
      - velocity
      - position

    state_interfaces:
      - velocity
      - position

joint_broadcaster:
  ros__parameters:
    joints:
      - rot_base_joint
      - arm1_joint
      - arm2_joint
      - arm3_joint
      - left_claw_joint
